### PR TITLE
fixes a tiny typo

### PR DESCRIPTION
**Pull request by Ordet**

### CODE REVIEW

**Comment by miss85246** [comment]
As a person whose mother tongue is not English, I'm not sure whether there are any mistakes here. Is this a syntactic error? 🤣  @Ordet

**Comment by Ordet** [comment]
Well, me neither. :D But yeah, there is. It's like the writer of the sentence changed his mind after writing "is", continued with "can be", and then, forgot to remove "is" (very common.) Not that the sentence has become vague or anything, but the docs are too good to have such tiny errors. (I saw some other tiny errors of this kind elsewhere in the docs, I'll fix them as soon as I can.)
@miss85246

**Review by miss85246 — COMMENTED** [review]
ok, I see

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
> It's like the writer of the sentence changed his mind after writing "is", continued with "can be", and then, forgot to remove "is"

:grimacing: Okay, I confess... it was me.

**Pull request merged**
