### PR TITLE
Release 21.9

### PR DESCRIPTION
**Pull request by ahopkins**
See #61. This is a continuation of that PR with a more general release branch.

## Translations

Pages that are ~crossed out~ are still in progress.

- [x] guide/deployment/running.md
- [x] guide/advanced/versioning.md
- [x] guide/advanced/streaming.md
- [x] guide/best-practices/blueprints.md
- [x] guide/basics/app.md
- [x] guide/basics/routing.md
- [x] guide/how-to/orm.md
- [x] guide/how-to/toc.md
~plugins/sanic-ext/configuration.md~
- [x] plugins/sanic-ext/convenience.md
- [x] plugins/sanic-ext/getting-started.md
- [x] plugins/sanic-ext/http/cors.md
- [x] plugins/sanic-ext/http/methods.md
- [x] plugins/sanic-ext/injection.md
~plugins/sanic-ext/openapi/advanced.md~
- [x] plugins/sanic-ext/openapi/autodoc.md
- [x] plugins/sanic-ext/openapi/basic.md
- [x] plugins/sanic-ext/openapi/decorators.md
- [x] plugins/sanic-ext/openapi/ui.md
~plugins/sanic-ext/openapi/validation.md~
- [x] ./.vuepress/config.js

### CODE REVIEW

**Comment by miss85246** [comment]
Nothing is difficult to the man who will try，I will do that on this weekend. 😃

**Comment by ahopkins** [comment]
> Nothing is difficult to the man who will try

One of my favorite quotes from Tolkien:

" Faithless is he that says farewell when the road darkens."

**Comment by miss85246** [comment]
I think I can translate from top to bottom, and you can translate from bottom to top. What do you think? @ZinkLu

**Comment by ahopkins** [comment]
@miss85246 and @ZinkLu Please note that I moved the "org" docs to their own directory and added a new sidebar for it. I did my best to try get the labels correct, but please double check my work there.

**Comment by miss85246** [comment]
@ahopkins  In the document `plugins/sanic-ext/http/methods`, I think this typesetting is simpler and more comfortable than the original typesetting. What do you think?

image

image

**Comment by ahopkins** [comment]
Yeah, I like the tabs. :+1:

**Comment by miss85246** [comment]
It seems that all translation works will be finished this weekend. 🥰

**Comment by miss85246** [comment]
@ahopkins  At present, all tasks are completed, and I will wait for the next document translation works. . . 😎

**Comment by ahopkins** [comment]
@miss85246 You are a rock star :star_struck:

**Review by miss85246 — COMMENTED** [review]
Are these all? I always thought there would be related documents of sanic_testing waiting to be translated. (•_•)?

**Comment by ahopkins** [comment]
I've got some more docs to add for the release. There might be one or two features of sanic-ext that remains without docs. I might not get to the sanic-testing docs until the weekend (after release)😵

**Comment by miss85246** [comment]
OK, please remember to inform me, I'm standing by. 😎

**Comment by ahopkins** [comment]
> OK, please remember to inform me, I'm standing by. 😎 

Sorry. Super crazy end to my week. I was planning to reach out to you today to let you know there were some changes.

**Pull request merged**
