### PR TITLE
Begin sanic-ext docs

### PR DESCRIPTION
**Pull request by ahopkins**
Documentation for `sanic-ext` (release with 21.9)

### CODE REVIEW

**Comment by ahopkins** [comment]
@sanic-org/docs This is still a WIP. I might also start using this branch for all 21.9 docs. Do you want to also translate the plugins docs?

**Comment by ZinkLu** [comment]
Yes, I personly like to contribute to all project's docs supported by SCO.

**Comment by ahopkins** [comment]
Okay. Since they are heavily WIP, maybe I'll create the zh stub when it's ready? That can be a cue for you? Maybe I'll rename this branch and we can both push commits to it.

**Comment by ZinkLu** [comment]
Okay.

**Comment by miss85246** [comment]
> @sanic-org/docs This is still a WIP. I might also start using this branch for all 21.9 docs. Do you want to also translate the plugins docs?

of course，I am very happy to have more Chinese documents 😎

**Pull request closed without merging**
