### PR TITLE
Update app.md and listeners.md

### PR DESCRIPTION
**Pull request by ProgramRipper**
Added some missing words.
补充了一些漏字、漏词。

-------------------------------

BTW, there is a strange phenomenon on "headers" page. Both [en](https://sanicframework.org/en/guide/basics/headers.html#response) and [zh](https://sanicframework.org/zh/guide/basics/headers.html#%E5%93%8D%E5%BA%94%E5%A4%B4-response-headers)
顺便一提，在“标头(Headers)”这一页面上有一奇怪的现象，在英语和中文页面中都有。
image
image
The contents of the red and blue boxes are exactly the same, but I didn't find out the reason from the source code. I think this may be due to the rendering error of the Markdown file.
红蓝两框的内容是完全一致的，但我没有在源码中找到原因。我想这也许是因为Markdown文件的渲染出错。

### CODE REVIEW

**Comment by ahopkins** [comment]
Thanks for the PR. I think I have noticed this once before about the headers page. I will see if I can figure it out.

**Comment by ZinkLu** [comment]
@ProgramRipper Thanks for the PR. 感谢老铁。

**Review by ZinkLu — APPROVED** [review]

**Comment by ahopkins** [comment]
I figured it out.... it seems to be a problem when going from a list to columns:

```
- `content-length`
- `content-type`
- `connection`
- `transfer-encoding`


---:1

Any other header that you would like to set can be done either in the route handler, or a response middleware.

:--:1

```python
@app.route("/")
async def handler(request):
    return text("Done.", headers={"content-language": "en-US"})

@app.middleware("response")
async def add_csp(request, response):
    response.headers["content-security-policy"] = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'"
```

:---
```

If I add an arbitrary line of text after the list, it renders as expected :man_shrugging:

**Comment by ahopkins** [comment]
image

**Pull request merged**
