### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by tuna2134**

### CODE REVIEW

**Comment by tuna2134** [comment]
Is it ok?

**Comment by ahopkins** [comment]
> Is it ok?

So far. I mean, I trust you about the translation since my Japanese is... nonexistent :laughing: 

But, you will need to incorporate changes throughout the whole config file.

**Comment by ahopkins** [comment]
I am marking this as a Draft PR

**Comment by ZinkLu** [comment]
Change A title?

**Comment by ZinkLu** [comment]
@tuna2134  Hi, I've commit the structure for you. you should foucus on:

- `src/ja` folder, these are main document.
- variable `ja_locales` in `src/.vuepress/config.js`. this effects catalogs.
- variable `ja` in `src/.vuepress/config.js`. this effects home page texts.
- property `defaultTitle` in `src/.vuepress/config.js`, line 1007. this effects some tips’s title.

to run a local server you should run: `npm run docs:dev`.

good luck to you!

**Comment by tuna2134** [comment]
Thx

**Comment by ahopkins** [comment]
@tuna2134 Please leave this in draft mode until it is ready for us to merge.

**Comment by tuna2134** [comment]
@ahopkins Please update

**Comment by ahopkins** [comment]
> @ahopkins Please update

Update what?

**Comment by tuna2134** [comment]
I'll be done soon.

**Comment by tuna2134** [comment]
@ahopkins

**Comment by ahopkins** [comment]
> @ahopkins

???

**Comment by miss85246** [comment]
awesome jobs！

**Comment by miss85246** [comment]
@tuna2134 Hi bro, what's the progress of your work ? we want  separate the localized configuration from `config.js` , 
you can saw more info from #100
If your work basically completed, I will do that after your branch merged，otherwise I will do that befor you.
You need to make another major change to your branch if I do that befor you. :sweat_smile:

I need your reply, thanks ! :wink:

**Comment by tuna2134** [comment]
> @tuna2134 Hi bro, what's the progress of your work ? we want  separate the localized configuration from `config.js` , 
> 
> you can saw more info from #100
> 
> If your work basically completed, I will do that after your branch merged，otherwise I will do that befor you.
> 
> You need to make another major change to your branch if I do that befor you. :sweat_smile:
> 
> 
> 
> I need your reply, thanks ! :wink:

Ok wait a moment please

**Comment by miss85246** [comment]
> Ok wait a moment please
OK，no problem, remember at me, after your work done ! @tuna2134

**Comment by tuna2134** [comment]
But I want to build own server.
Because, my friend want to see Japanese document.

**Comment by tuna2134** [comment]
Oh mistake

**Comment by tuna2134** [comment]
How to reopen a pull request.

**Comment by tuna2134** [comment]
@ahopkins Please reopen this pull request.

**Comment by tuna2134** [comment]
@miss85246

**Comment by miss85246** [comment]
@tuna2134  I see, but I don't think merge branch will effect you build it on your own server.
If you want let your friends browse it on [sanicframework.org](https://sanicframework.org),
you should merge it here, not build on your own server.

**Comment by tuna2134** [comment]
> @tuna2134 I see, but I don't think merge branch will effect you build it on your own server.
> If you want let your friends browse it on [sanic.dev](https://sanic.dev),
> you should merge it here, not build on your own server.

Ok
and I again to pull request.
https://github.com/sanic-org/sanic-guide/pull/101

**Pull request closed without merging**
