### PR TITLE
update exceptions.md: recommend people to raise exception instead of use 'abort'

### PR DESCRIPTION
**Pull request by artcg**

### CODE REVIEW

**Review by ahopkins — APPROVED** [review]
LGTM. @sanic-org/docs How do we want to handle translations?

**Comment by miss85246** [comment]
I'll deal with this file tonight @ahopkins @artcg

**Comment by artcg** [comment]
Awesome! Thanks @miss85246

**Comment by miss85246** [comment]
OK, work done, please merge it @ahopkins

**Comment by miss85246** [comment]
> Awesome! Thanks @miss85246

you are welcome 😄

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
