### PR TITLE
Corrected a minor mistake in the docs 

### PR DESCRIPTION
**Pull request by YuvrajGeek**
image

Found it here: https://sanicframework.org/en/guide/basics/cookies.html#writing
and here too: https://sanicframework.org/zh/guide/basics/cookies.html

### CODE REVIEW

**Comment by ZinkLu** [comment]
Could you please make another change for https://github.com/sanic-org/sanic-guide/blob/main/src/zh/guide/basics/cookies.md#%E5%86%99%E5%85%A5writing.

**Comment by YuvrajGeek** [comment]
> Could you please make another change for https://github.com/sanic-org/sanic-guide/blob/main/src/zh/guide/basics/cookies.md#%E5%86%99%E5%85%A5writing.

Done :)

**Review by ahopkins — APPROVED** [review]
Awesome thanks :tada:

**Comment by YuvrajGeek** [comment]
> Awesome thanks 🎉

NP :smile:

**Pull request merged**
