### PR TITLE
adding zh trans for 21.6 release info; fix some typo;

### PR DESCRIPTION
**Pull request by ZinkLu**

### CODE REVIEW

**Comment by ahopkins** [comment]
Looks good, anything I can do to help?

**Comment by ahopkins** [comment]
I will try harder for the next release to get them done earlier in the process.

**Comment by ZinkLu** [comment]
> Looks good, anything I can do to help?

Yup, Please take a review before merge this PR. Some parts have not yet been translated.

> I will try harder for the next release to get them done earlier in the process.

It's okay for me not to release at the same time. Others may see the new content and participate in the translation (hopefully).

**Review by ahopkins — APPROVED** [review]

**Comment by ZinkLu** [comment]
Hi @ahopkins , I think it's ready to merge. 

Please take anohter look on the changes in en part. I fixed some typos, changed tab `new in 21.3` into `new in 21.6`, and did some other changes.

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
