### PR TITLE
Changes to make docs ready for 21.3 launch

### PR DESCRIPTION
**Pull request by ahopkins**
This adds the documentation needed to get the docs ready for the 21.3 launch. I anticipate some more commits once the last few PRs are approved and merged into the core repository.

@ZinkLu and @miss85246, can you guys add commits to this PR with translations?

Also includes:
- [#1731](https://github.com/sanic-org/sanic/issues/1731)
- [#1608](https://github.com/sanic-org/sanic/issues/1608)
- [#1218](https://github.com/sanic-org/sanic/issues/1218)

### CODE REVIEW

**Comment by ahopkins** [comment]
```
defaultTitle: {
  "/": "NEW",
  "/zh/": "新的",
},
```

:point_up:  Is this correct?

**Review by ZinkLu — COMMENTED** [review]
Yes! NEW == 新的

**Comment by ahopkins** [comment]
I sometimes doubt Google Translate. Glad to know that it worked in this simple context.

**Review by ZinkLu — COMMENTED** [review]
Yes! NEW == 新的; Have tried locally, the config works fine in chinese parts.

**Comment by ahopkins** [comment]
> Yes! NEW == 新的; Have tried locally, the config works fine in chinese parts.

There are a few places where [we override the default](https://github.com/sanic-org/sanic-guide/pull/11/files#diff-5f1e892fc0dcf66497a6f690d01aa4e2b0786afabec9be71ca54c79d91d4d8d0R7). I would be curious to know if Chinese is also supported here.

**Comment by ahopkins** [comment]
@ZinkLu  and @miss85246 , I just added two documents that are more "organizational" than documentation. One covers various policies for Sanic, the other is the SCOPE (the document that describes how Sanic Community Org funcitons). I am not sure you want to go about translating those, especially the SCOPE. It is a long document, and really not too relevant for what you are doing. I imagine there will also be some changes to it before the end of the year, so I would hate for you to spend too much time treanslating that.

**Comment by miss85246** [comment]
It seems that a lot of files have been modified. I will take time to compare and modify the translation. Recently, I was busy. The company asked me to use golang to complete the HIDS program, and I felt a little hard.
The progress of translation may be much slower than before. 😢

**Comment by ZinkLu** [comment]
> It seems that a lot of files have been modified. I will take time to compare and modify the translation. Recently, I was busy. The company asked me to use golang to complete the HIDS program, and I felt a little hard.
> The progress of translation may be much slower than before. 😢

NP, I'll handle these new content. 
BTW, golang is very esay to learn and easy to use. you can talk to me if you have any issue.

**Comment by ZinkLu** [comment]
@ahopkins I think we should try to translate these "organizational" content, It seems very important to the community.

**Comment by miss85246** [comment]
> NP, I'll handle these new content.
> BTW, golang is very esay to learn and easy to use. you can talk to me if you have any issue.

Indeed. Golang is not very difficult, but it is very unaccustomed to it, it is less efficient, the leadership urged the tight, and it is done independently, so I feel a little embarrassed

**Review by ZinkLu — APPROVED** [review]

**Comment by ahopkins** [comment]
> @ahopkins I think we should try to translate these "organizational" content, It seems very important to the community.

I don't disagree. Just meant that I think they are less important right now. Their utility is more for people wishing to be more deeply involved in the community and not just someone who wants to know how to use Sanic.

There are a few new pages and some additions on a few pages with "new" stuff. The majority of the files have only changed their location. The PR is smaller than it would appear by looking at the file list.

**Comment by ZinkLu** [comment]
> There are a few new pages and some additions on a few pages with "new" stuff. The majority of the files have only changed their location. The PR is smaller than it would appear by looking at the file list.

Sure, we'll foucus on main content, our target is make all content translated by the date 21.3 released.I shall try to translate community announcement if time permitting.

I wonder whether all new content is on translation branch now? maybe another merge from lanuch should be done?

**Comment by ahopkins** [comment]
I don't want to merge the launch branch until we release. Make commits directly on that branch with translations. It should have all the pages.

**Comment by ZinkLu** [comment]
NP

**Review by miss85246 — APPROVED** [review]

**Comment by miss85246** [comment]
I agree to translate "organizational" doc. Infact, I also hope a lot of people interested of sanic. For those who are interested, this document will be a good guide for participating.

**Comment by miss85246** [comment]
@ZinkLu Lu, please review the PR and merge it. I think maybe I should be able to finish the translation of the updated part this weekend.

**Review by ZinkLu — APPROVED** [review]

**Comment by ahopkins** [comment]
This should not be merged until we launch. Two weeks: March 21 is target date.

**Comment by ZinkLu** [comment]
@miss85246 commits on the launch branch directly. I should be avaiable on this weekend too.

**Comment by miss85246** [comment]
@ZinkLu nice work! 👍🏼 
I worked overtime for two days. I have no time to translate these documents. 😢  
Maybe I can take time to check the unity and fluency of the translated documents. It depends. I'll leave the rest to you. ⚡

**Comment by ahopkins** [comment]
@miss85246 thanks for the hard work on this.

**Comment by ahopkins** [comment]
@sanic-org/docs What pages are left in Chinese? I just added `signals.md`, and a change to `response.md` and `app.md`: [commit 01db4ea08833aadfaa53c125478c6d1c9c2f0f8c](https://github.com/sanic-org/sanic-guide/pull/11/commits/01db4ea08833aadfaa53c125478c6d1c9c2f0f8c).

I _think_ there should not be any more changes to existing pages. I want to get probably one more page to the Deployment section.

**Comment by ZinkLu** [comment]
we should be able to track the change by commits. all content had completed before your last commit. So I shall start work on these part.

**Comment by ahopkins** [comment]
@ZinkLu  and @miss85246 I think this is the last set of pages for the initial launch. Afterwards, we can work on getting the remaining pages up. Let me know if you think anything critical is missing.

**Comment by miss85246** [comment]
when I recheck the doc of `best-practices/exceptions.md`, The last lesson `Auto` said that `FALLBACK_ERROR_FORMAT` still **experimental feature**. I remembered it was added in v20.9. the v20.12 was released, and now , we will releasev21.3.
so, I think it's should be formal feature, right?

**Comment by ahopkins** [comment]
Good question. The fallback is no longer experimental. However, the ultimate goal is for "auto" to be the default. However, it is not ready to be default. It has a fairly "dumb" check to decode which to use. The plan is for it to do some start up time analysis of the handler to decide which to use.

**Comment by ahopkins** [comment]
Looks like the new `mermaid` charts on `listeners.md` and `middleware.md` will play nicely with Chinese characters if you want to add more appropriate descriptions.

**Comment by miss85246** [comment]
Okay, I see. Let me see what's change of these docs and  what appropriate descriptions can I add.

**Comment by ZinkLu** [comment]
@miss85246 I've add some description in mermaid, please review these changes.

**Comment by ZinkLu** [comment]
@ahopkins I've beenig impressed by the AST router, it  has a great speed improvement compare to 20.12. should we have a benchmark with other frameworks? I can do that.

Or. We cat put a [forum link](https://community.sanicframework.org/t/a-fast-new-router/649)  or [github link](https://github.com/sanic-org/sanic-router) in document.

**Comment by ahopkins** [comment]
Agreed. There are some more performance boosts planned for this year.

Do you mean benchmarks of frameworks (sanic v flask)? Or, if the router?

I am not really in favor of benchmarking frameworks on our official docs.

**Comment by ZinkLu** [comment]
I meant to have a benchmarks of frameworks (sanic vs flask vs others). But we probably shouldn't do if you are not willing to.

I suggest to have a github link (or both github and forum links) in `Router overhaul` section.

If anything a can do please let me know.

**Comment by ahopkins** [comment]
> I suggest to have a github link (or both github and forum links) in `Router overhaul` section.

@ZinkLu I added some links in the release notes. I do not think it is appropriate to link to the conversations from inside the documentation itself.

**Comment by ahopkins** [comment]
There were some other small tweaks, and I think I noticed that the Chinese docs also need the new `<date:ymd>` path parameter on the `routing.md` page.

**Comment by ZinkLu** [comment]
> There were some other small tweaks, and I think I noticed that the Chinese docs also need the new `<date:ymd>` path parameter on the `routing.md` page.

There should be some content that have not been translated yet, such as `running.md`. we'll deal with them recently. 
BTW. Can English part be freezed by this Friday(3/19) ? If then, we probably can have a fully review on Saturday. 

Release date is 3/21, right?

**Comment by ahopkins** [comment]
> Can English part be freezed by this Friday(3/19) ?

:+1: I will stop updating it 2021-03-19 00:00:00 UTC

> Release date is 3/21, right?

Yes. Probably around 9am UTC.

**Comment by miss85246** [comment]
@ahopkins @ZinkLu 
Hey, guys, a good news,  we have checked all the documents except `running.md`, which has not been translated.
All documents will be displayed in a uniform format. 
The rest of the questions are use the same proper nouns.
Looking forward to the document release 🤩🤩🤩

**Comment by ahopkins** [comment]
Amazing! 😁 

I am excited too for this release and for these docs. I am curious to check to see if the vuepress plugin is smart enough to check headers and automatically display the Chinese content when requested. We seem to average about 10-15% of our traffic from China.

**Comment by ahopkins** [comment]
> @ahopkins @ZinkLu
> Hey, guys, a good news, we have checked all the documents except `running.md`, which has not been translated.
> All documents will be displayed in a uniform format.
> The rest of the questions are use the same proper nouns.
> Looking forward to the document release star_struckstar_struckstar_struck

I think there are some changes from this commit missing: https://github.com/sanic-org/sanic-guide/pull/11/commits/588aef48a8a21cd1b440668da6cf53cc38b96a9b

**Comment by ZinkLu** [comment]
Busy week, will do tonight.

**Comment by ahopkins** [comment]
> Busy week, will do tonight.

Not criticizing, just a reminder. 

I think this is the last of the changes. Unless there is something **SUPER** important missing, I do not think I will have any more changes today.

**Comment by miss85246** [comment]
work down, is there anything left out? Think again carefully, we need a perfect release conference!🎉🎉🎉

**Comment by ahopkins** [comment]
👏👏👏 Job well done. If only I could read it 😆

**Comment by ZinkLu** [comment]
:thinking: I am pretty sure there are some contents has not been translated yet. A full review should be done.

**Comment by miss85246** [comment]
This time， I run the  program and found out all untranslated content against en. See [here](https://github.com/sanic-org/sanic-guide/pull/11/commits/afb72e9f516897f1765e33695e29deaae06d84c2) for details

**Comment by miss85246** [comment]
@ZinkLu  `Connection` should be translated as `连接` or `链接` ? I think it should be `连接`, and  `link` corresponds to `链接`

**Comment by ZinkLu** [comment]
> @ZinkLu `Connection` should be translated as `连接` or `链接` ? I think it should be `连接`, and `link` corresponds to `链接`

Ok, feel free to make a change and have another review if you are available.

**Review by ZinkLu — COMMENTED** [review]
looks all good to me.

**Pull request merged**
